language: node_js
node_js: 12


stages:
  - lint

jobs:
  include:
  - stage: Transpile
    name: transpile
    install: npm install
    script: npm run build

  - stage: global testing
    name: compile
    install: npm install
    script: npm build

  - stage: global testing
    name: tests
    install: npm install
    script: npm test
    
  - stage: deployement
    name: skip the heroku TODO
    script: skip